# Generated by Django 6.0.5 on 2026-05-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='duracao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
