# Generated by Django 6.0.5 on 2026-05-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_filme_duracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='poster',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
