# Generated by Django 6.0.5 on 2026-05-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_filme_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaoedicao',
            name='dados_antigos',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
