# Generated by Django 6.0.5 on 2026-05-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_solicitacaoedicao_dados_antigos'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='status_solicitacao',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADA', 'Aprovada'), ('DECLINADA', 'Declinada')], default='PENDENTE', max_length=20),
        ),
    ]
